### ISSUE TITLE
Feature: Provide option of returning the aggregate function's output as array instead of string

### ISSUE THREAD

**Issue by ooi18-1** [CIDRAM/Aggregator#11]
Hi,

Thank you for the work on this wonderful library. Just one question after playing around with this library, can we choose to have the aggregate function returning the output as array instead of the default string? Just a thought though :).

**Comment by Maikuolan** [comment]
Thank you for the compliment, and my apologies for the delayed reply. I've pushed some new commits with code changes just now so that it's now possible to return the output as an array instead of the default string. :-)

The Aggregator (as of now) can be instructed to return the aggregated data as an array via the existing integer parameter supplied to the constructor (0 [the default value] or 1 for a string; 2 or 3 for an array).

```PHP
    /**
     * Constructor.
     *
     * @param int $Mode Specifies the format to use for the Aggregator's output.
     *      0 = CIDR notation; Data as a line-separated string [Default].
     *      1 = Netmask notation; Data as a line-separated string.
     *      2 = CIDR notation; Data as an array.
     *      3 = Netmask notation; Data as an array.
     * @return void
     */
```

I haven't yet pushed a new tag/release for the changes, but I'll get onto that shortly.

**Comment by Maikuolan** [comment]
New tag/release pushed. :-)
